spring:
  datasource:
    url: jdbc:mysql://localhost:3306/priyansh?createDatabaseIfNotExist=true
    username: root
    password: 9027707502
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

jwt:
  secret: portfolio-backend-super-secret-key-123456
  expiration: 86400000

