# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/priyansh?createDatabaseIfNotExist=true
#     username: root
#     password: 

#   jpa:
#     show-sql: true

# logging:
#   level:
#     org.hibernate.SQL: DEBUG
#     org.springframework.security: DEBUG

# jwt:
#   secret: portfolio-backend-super-secret-key-123456
#   expiration: 86400000
